
x bug - When you insist to add empty partner contact name or position after error was raised the first time , 
	an uncontrolled exception is raised with the message :
		raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)

	You can solve it, checking before emiting to database the sql, like:
	
	class Partner_Form: 
		.
		.
		.
	
		def contacts_correct(self, contacts):
			for c in contacts:
				if not c.name or c.position:
					return False
			else:
				return True 

		def save(self):
			....

			if not self.contacts_correct(self.partner.contacts):
				QMessageBox.critical(self, 'Error - Update', 'Contact with empty name or position are not valid')



	if I save a partner, then i cant remove a partner an save again, an error is launched.

	

		