qt.gui.icc: Unsupported ICC profile class 70727472
Traceback (most recent call last):
  File "C:\Users\Andrei\Desktop\Projects\euromedia\app\models.py", line 1747, in data
    financial_status_string = proforma.financial_status_string
  File "C:\Users\Andrei\Desktop\Projects\euromedia\app\db.py", line 1008, in financial_status_string
    return self.invoice.financial_status_string
  File "C:\Users\Andrei\Desktop\Projects\euromedia\app\db.py", line 1244, in financial_status_string
    x = self.paid - self.applied
  File "C:\Users\Andrei\Desktop\Projects\euromedia\app\db.py", line 1269, in applied
    _relationship = self.wasted_discounts if self.is_credit_note else self.return_discounts
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 453, in __get__
    return self.impl.get(state, dict_)
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 897, in get
    value = self.callable_(state, passive)
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\orm\strategies.py", line 874, in _load_for_state
    return self._emit_lazyload(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\orm\strategies.py", line 1037, in _emit_lazyload
    result = session.execute(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1662, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\sql\lambdas.py", line 481, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1933, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\sqlalchemy\engine\default.py", line 691, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\mysql\connector\cursor.py", line 577, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\mysql\connector\connection.py", line 695, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "C:\Users\Andrei\Desktop\Projects\euromedia\venv\lib\site-packages\mysql\connector\connection.py", line 571, in _handle_result
    elif packet[4] == 0:
IndexError: bytearray index out of range
